### ISSUE TITLE
Bump sw-precache version to v5

### ISSUE THREAD

**Issue by caleb531** [denar90/sw-precache-brunch#11]
Hi @denar90,

Since [sw-precache](https://github.com/GoogleChrome/sw-precache) v5.0.0, an important change was introduced in response to a new browser restriction on redirected requests (see [the v5.0.0 release notes](https://github.com/GoogleChrome/sw-precache/releases/tag/5.0.0)). However, this Brunch plugin is currently locked at v4 (due to semver restrictions) in package.json.

![screen shot 2017-05-05 at 4 55 46 pm](https://cloud.githubusercontent.com/assets/872474/25768002/bcf26c0c-31b3-11e7-8c52-065258f5377a.png)

Can we please bump the version number of `sw-precache` to the latest v5 release? I suppose since v5 is a major release, you would also need to push a new major release of this plugin to respect semver (so v2.0.0).

Thanks,
Caleb

P.S. I see a PR for this change has already been suggested in #10. Please consider merging it in.

**Comment by denar90** [comment]
Hi, thanks. I've also merged all stuff related to v2 in #9.

**Comment by denar90** [comment]
published 🚢 
@caleb531 hope to get your feedback about how new version works for you :)

**Comment by caleb531** [comment]
Yep, it works great! Though for what it's worth, I noticed that v2.0.0 is missing a GitHub release/tag. ;)

Anyway, thank you for the quick work, @denar90!

**Comment by denar90** [comment]
Thanks, tag has been created.
